apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wiki-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /wiki
          backend:
            serviceName: wiki
            servicePort: 80
        - path: /
          backend:
            serviceName: wiki
            servicePort: 3000